import { useEffect, useId, useRef, useState, type KeyboardEvent, type ReactNode } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import type { FriendRequest, PresenceEvent, RefereeInvite, RoomInvite, RoomPlayMode, SocialUser } from "@ottv2/contracts";
import { routes } from "../app/routes";
import { Button, LoadingState, Modal, useToast } from "../components/ui";
import { ApiError } from "../services/http/apiError";
import { acceptInvite, blockUser, createInvite, getFriends, getInvites, getRequests, rejectInvite, removeFriend, searchUsers, sendFriendRequest, subscribeToPresence, updateFriendRequest } from "../services/social/socialApi";
import { acceptRefereeInvite, declineRefereeInvite, getRefereeInvites, inviteReferee } from "../services/rooms/roomApi";
import { loginReturnPath } from "../services/auth/returnUrl";

type Tab = "friends" | "incoming" | "sent" | "search";
type InviteRole = "PLAYER" | "REFEREE";
type Composer = { kind: "idle" } | { kind: "pending" } | { kind: "success"; value: string; role: InviteRole } | { kind: "error" | "expired"; message: string };
const isExpired = (reason: unknown) => reason instanceof ApiError && (reason.code === "INVITE_INVALID" || reason.status === 410);
const profilePath = (username: string) => "/profile/" + encodeURIComponent(username);

export default function FriendsPageR12() {
  const navigate = useNavigate(); const location = useLocation(); const { notify } = useToast();
  const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [error, setError] = useState("");
  const [tab, setTab] = useState<Tab>("friends"); const [friends, setFriends] = useState<SocialUser[]>([]); const [incoming, setIncoming] = useState<FriendRequest[]>([]); const [sent, setSent] = useState<FriendRequest[]>([]);
  const [invites, setInvites] = useState<RoomInvite[]>([]); const [refereeInvites, setRefereeInvites] = useState<RefereeInvite[]>([]); const [query, setQuery] = useState(""); const [results, setResults] = useState<SocialUser[]>([]);
  const [target, setTarget] = useState<SocialUser | null>(null); const [roomId, setRoomId] = useState(""); const [role, setRole] = useState<InviteRole>("PLAYER"); const [playMode, setPlayMode] = useState<RoomPlayMode>("MANUAL"); const [composer, setComposer] = useState<Composer>({ kind: "idle" });
  const [pending, setPending] = useState<string | null>(null); const [blocked, setBlocked] = useState<SocialUser | null>(null); const [stale, setStale] = useState(false); const warned = useRef(false); const searchSeq = useRef(0);

  const reload = async () => {
    setState("loading");
    try {
      const values = await Promise.all([getFriends(), getRequests("incoming"), getRequests("sent"), getInvites(), getRefereeInvites()]);
      setFriends(values[0].friends); setIncoming(values[1].requests); setSent(values[2].requests); setInvites(values[3].invites); setRefereeInvites(values[4].invites); setState("ready");
    } catch (reason) { if (reason instanceof ApiError && reason.status === 401) navigate(loginReturnPath(location)); else { setError(reason instanceof ApiError ? reason.message : "Không thể tải dữ liệu bạn bè."); setState("error"); } }
  };
  useEffect(() => {
    void reload();
    const stop = subscribeToPresence((event: PresenceEvent) => { setStale(false); warned.current = false; setFriends((current) => current.map((friend) => friend.userId === event.user.userId ? { ...friend, presence: event.user.presence } : friend)); }, () => { setStale(true); if (!warned.current) { warned.current = true; notify("Trạng thái online đang cũ. Bạn vẫn có thể dùng các thao tác an toàn.", "warning"); } });
    return stop;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [navigate, notify]);
  useEffect(() => {
    const sequence = ++searchSeq.current;
    if (tab !== "search" || query.trim().length < 2) { setResults([]); return; }
    const timer = window.setTimeout(() => { searchUsers(query).then((response) => { if (sequence === searchSeq.current) setResults(response.results); }).catch((reason) => { if (sequence === searchSeq.current) notify(reason instanceof ApiError ? reason.message : "Không thể tìm người chơi.", "error"); }); }, 300);
    return () => window.clearTimeout(timer);
  }, [query, tab, notify]);

  const run = async (key: string, action: () => Promise<unknown>, message: string) => { if (pending) return; setPending(key); try { await action(); notify(message, "success"); await reload(); } catch (reason) { notify(reason instanceof ApiError ? reason.message : "Thao tác không thành công.", "error"); } finally { setPending(null); } };
  const openInvite = (user: SocialUser) => { setTarget(user); setRoomId(""); setRole("PLAYER"); setPlayMode("MANUAL"); setComposer({ kind: "idle" }); };
  const closeInvite = () => { if (composer.kind !== "pending") { setTarget(null); setComposer({ kind: "idle" }); } };
  const sendInvite = async () => {
    if (!target || composer.kind === "pending") return;
    const normalized = roomId.trim().toUpperCase(); if (!/^[A-Z0-9]{6}$/.test(normalized)) { notify("Room ID phải gồm 6 ký tự.", "warning"); return; }
    setComposer({ kind: "pending" });
    try {
      if (role === "REFEREE") { const response = await inviteReferee(normalized, target.userId); setComposer({ kind: "success", value: response.invite.inviteId, role }); notify("Đã gửi lời mời làm Trọng tài.", "success"); }
      else { const response = await createInvite(normalized, target.userId, playMode); setComposer({ kind: "success", value: response.invite.token, role }); notify("Đã gửi lời mời vào phòng.", "success"); }
    } catch (reason) { const expired = isExpired(reason); const message = expired ? "Phòng không còn nhận lời mời hoặc lời mời đã hết hạn." : reason instanceof ApiError ? reason.message : "Không thể gửi lời mời."; setComposer({ kind: expired ? "expired" : "error", message }); notify(message, expired ? "warning" : "error"); }
  };
  const acceptPlayer = async (invite: RoomInvite) => { if (pending) return; setPending(invite.token); try { const response = await acceptInvite(invite.token); setInvites((current) => current.filter((item) => item.token !== invite.token)); notify("Đã vào phòng được mời.", "success"); const room = response.room as { roomId?: string }; if (room.roomId) navigate("/room/" + room.roomId); } catch (reason) { if (isExpired(reason)) setInvites((current) => current.filter((item) => item.token !== invite.token)); notify(isExpired(reason) ? "Lời mời đã hết hạn hoặc không còn hiệu lực." : reason instanceof ApiError ? reason.message : "Không thể nhận lời mời vào phòng.", isExpired(reason) ? "warning" : "error"); } finally { setPending(null); } };
  const rejectPlayer = async (invite: RoomInvite) => { if (pending) return; setPending(invite.token); try { await rejectInvite(invite.token); setInvites((current) => current.filter((item) => item.token !== invite.token)); notify("Đã từ chối lời mời vào phòng.", "success"); } catch (reason) { notify(reason instanceof ApiError ? reason.message : "Không thể từ chối lời mời.", "error"); } finally { setPending(null); } };
  const acceptReferee = async (invite: RefereeInvite) => { if (pending) return; setPending(invite.inviteId); try { const response = await acceptRefereeInvite(invite.inviteId); setRefereeInvites((current) => current.filter((item) => item.inviteId !== invite.inviteId)); notify("Đã nhận vai trò Trọng tài.", "success"); const room = response.room as { roomId?: string }; if (room.roomId) navigate("/room/" + room.roomId); } catch (reason) { if (reason instanceof ApiError && (reason.status === 404 || reason.status === 409)) setRefereeInvites((current) => current.filter((item) => item.inviteId !== invite.inviteId)); notify(reason instanceof ApiError ? reason.message : "Không thể nhận lời mời Trọng tài.", "error"); } finally { setPending(null); } };
  const rejectReferee = async (invite: RefereeInvite) => { if (pending) return; setPending(invite.inviteId); try { await declineRefereeInvite(invite.inviteId); setRefereeInvites((current) => current.filter((item) => item.inviteId !== invite.inviteId)); notify("Đã từ chối lời mời Trọng tài.", "success"); } catch (reason) { notify(reason instanceof ApiError ? reason.message : "Không thể từ chối lời mời Trọng tài.", "error"); } finally { setPending(null); } };

  if (state === "loading") return <LoadingState fullPage label="Đang tải bạn bè…" />;
  if (state === "error") return <section className="placeholder friends-visual-shell friends-error"><p className="eyebrow">BẠN BÈ</p><h1>Không thể tải bạn bè</h1><p className="form-intro">{error}</p><Button onClick={() => void reload()}>Thử lại</Button></section>;
  const incomingCount = incoming.length + invites.length + refereeInvites.length;
  return <>
    <section className="friends-page friends-visual-shell">
      <header className="friends-header"><div><p className="eyebrow">KẾT NỐI NGƯỜI CHƠI</p><h1>Bạn bè</h1><p className="form-intro">Kết nối riêng tư; trạng thái online chỉ hiển thị cho bạn bè.</p></div><div className="friends-header-actions">{stale && <Button variant="ghost" onClick={() => void reload()}>Làm mới trạng thái</Button>}<Link className="button secondary" to={routes.profile}>Hồ sơ của tôi</Link></div></header>
      {stale && <p className="social-stale" role="status">Presence đang tạm gián đoạn — thông tin hiển thị có thể cũ, quyền riêng tư vẫn được giữ.</p>}
      <div className="friends-tabs" role="tablist" aria-label="Khu vực bạn bè">{([ ["friends", "BẠN BÈ"], ["incoming", "LỜI MỜI"], ["sent", "ĐÃ GỬI"], ["search", "TÌM NGƯỜI CHƠI"] ] as const).map(([value, label]) => <button className={"friends-tab " + (tab === value ? "active" : "")} role="tab" aria-selected={tab === value} type="button" key={value} onClick={() => setTab(value)}>{label}{value === "incoming" && incomingCount > 0 ? " · " + incomingCount : ""}</button>)}</div>
      {tab === "friends" && <FriendList users={friends} pending={pending} onInvite={openInvite} onRemove={(user) => void run("remove:" + user.userId, () => removeFriend(user.userId), "Đã xoá @" + user.username + " khỏi danh sách bạn bè.")} onBlock={setBlocked} />}
      {tab === "incoming" && <Incoming requests={incoming} invites={invites} refereeInvites={refereeInvites} pending={pending} onAcceptRequest={(request) => void run("request:" + request.requestId, () => updateFriendRequest(request.requestId, "accept"), "Đã chấp nhận lời mời kết bạn.")} onRejectRequest={(request) => void run("request:" + request.requestId, () => updateFriendRequest(request.requestId, "reject"), "Đã từ chối lời mời.")} onAcceptInvite={acceptPlayer} onRejectInvite={rejectPlayer} onAcceptRefInvite={acceptReferee} onRejectRefInvite={rejectReferee} />}
      {tab === "sent" && <RequestList requests={sent} pending={pending} actionLabel="Hủy yêu cầu" onAction={(request) => void run("request:" + request.requestId, () => updateFriendRequest(request.requestId, "cancel"), "Đã hủy yêu cầu kết bạn.")} />}
      {tab === "search" && <SearchPanel query={query} onQuery={setQuery} results={results} pending={pending} onAdd={(user) => void run("request:" + user.userId, () => sendFriendRequest(user.userId), "Đã gửi lời mời tới @" + user.username + ".")} onBlock={setBlocked} />}
    </section>
    <Modal open={Boolean(target)} title="Mời vào phòng" description={target ? "Mời @" + target.username + " · quyền được máy chủ kiểm tra" : undefined} onClose={closeInvite}><div className="form-stack">
      <label>Room ID<input aria-label="Room ID" value={roomId} onChange={(event) => { setRoomId(event.target.value.toUpperCase()); if (composer.kind !== "idle") setComposer({ kind: "idle" }); }} maxLength={6} placeholder="ABC234" disabled={composer.kind === "pending" || composer.kind === "success"} /></label>
      <label>Vai trò<select aria-label="Vai trò lời mời" value={role} onChange={(event) => setRole(event.target.value as InviteRole)} disabled={composer.kind === "pending" || composer.kind === "success"}><option value="PLAYER">Người chơi</option><option value="REFEREE">Trọng tài</option></select></label>
      {role === "PLAYER" && <label>Chế độ phòng<select aria-label="Chế độ phòng" value={playMode} onChange={(event) => setPlayMode(event.target.value as RoomPlayMode)} disabled={composer.kind === "pending" || composer.kind === "success"}><option value="MANUAL">Chơi trực tiếp</option><option value="BOT">Đấu chương trình</option></select><span className="form-hint">Máy chủ sẽ từ chối nếu chế độ không khớp phòng.</span></label>}
      {role === "REFEREE" && <p className="form-hint">Trọng tài phải là tài khoản đăng nhập; Guest không thể nhận vai trò này.</p>}
      {composer.kind === "pending" && <p className="form-hint" role="status">Đang gửi lời mời…</p>}{(composer.kind === "error" || composer.kind === "expired") && <p className="form-error" role="alert">{composer.message}</p>}
      {composer.kind === "success" && <div className="invite-token" role="status"><strong>{composer.role === "REFEREE" ? "Mã lời mời Trọng tài" : "Token một lần"}</strong><code aria-label={composer.role === "REFEREE" ? "Mã lời mời Trọng tài" : "Token lời mời một lần"}>{composer.value}</code><span>{composer.role === "REFEREE" ? "Người được mời phải chấp nhận trước khi phòng bắt đầu." : "Token chỉ dùng một lần và được máy chủ kiểm tra."}</span></div>}
      <div className="modal-actions"><Button variant="secondary" onClick={closeInvite}>{composer.kind === "success" ? "Đóng" : "Hủy"}</Button>{composer.kind !== "success" && <Button pending={composer.kind === "pending"} onClick={() => void sendInvite()}>{composer.kind === "expired" ? "Thử lại" : "Gửi lời mời"}</Button>}</div>
    </div></Modal>
    <Modal open={Boolean(blocked)} title={blocked ? "Chặn " + blocked.displayName + "?" : "Chặn người chơi?"} description="Người này sẽ không thể gửi lời mời kết bạn, mời vào phòng hoặc xem trạng thái của bạn." onClose={() => setBlocked(null)}><div className="modal-actions"><Button variant="secondary" onClick={() => setBlocked(null)}>Hủy</Button><Button variant="danger" pending={pending === "block:" + blocked?.userId} onClick={() => { if (blocked) { const user = blocked; setBlocked(null); void run("block:" + user.userId, () => blockUser(user.userId), "Đã chặn @" + user.username + "."); } }}>Chặn</Button></div></Modal>
  </>;
}

function FriendList({ users, pending, onInvite, onRemove, onBlock }: { users: SocialUser[]; pending: string | null; onInvite: (user: SocialUser) => void; onRemove: (user: SocialUser) => void; onBlock: (user: SocialUser) => void }) { if (!users.length) return <EmptySocial title="Chưa có bạn bè" copy="Tìm một người chơi để bắt đầu kết nối." />; return <div className="friend-grid">{users.map((user) => <SocialCard key={user.userId} user={user} actions={<><Button variant="secondary" onClick={() => onInvite(user)} disabled={user.presence === "IN_GAME"}>Mời chơi</Button><ActionsMenu user={user} pending={pending} onRemove={onRemove} onBlock={onBlock} /></>} />)}</div>; }
function ActionsMenu({ user, pending, onRemove, onBlock }: { user: SocialUser; pending: string | null; onRemove: (user: SocialUser) => void; onBlock: (user: SocialUser) => void }) { const [open, setOpen] = useState(false); const root = useRef<HTMLDivElement>(null); const trigger = useRef<HTMLButtonElement>(null); const menuId = useId(); useEffect(() => { if (!open) return undefined; const closeOutside = (event: PointerEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); }; const closeEscape = (event: globalThis.KeyboardEvent) => { if (event.key === "Escape") { setOpen(false); window.setTimeout(() => trigger.current?.focus(), 0); } }; document.addEventListener("pointerdown", closeOutside); document.addEventListener("keydown", closeEscape); const frame = window.requestAnimationFrame(() => root.current?.querySelector<HTMLElement>("[role=menuitem]")?.focus()); return () => { window.cancelAnimationFrame(frame); document.removeEventListener("pointerdown", closeOutside); document.removeEventListener("keydown", closeEscape); }; }, [open]); const move = (event: KeyboardEvent<HTMLDivElement>) => { const items = Array.from(root.current?.querySelectorAll<HTMLElement>("[role=menuitem]") ?? []); const index = items.indexOf(document.activeElement as HTMLElement); if (["ArrowDown", "ArrowUp", "Home", "End"].includes(event.key)) { event.preventDefault(); const next = event.key === "Home" ? 0 : event.key === "End" ? items.length - 1 : (index + (event.key === "ArrowDown" ? 1 : -1) + items.length) % items.length; items[next]?.focus(); } if (event.key === "Escape") { event.preventDefault(); setOpen(false); trigger.current?.focus(); } }; return <div className="friend-action-menu" ref={root}><button ref={trigger} className="icon-button friend-menu-trigger" type="button" aria-label={"Thao tác với " + user.displayName} aria-haspopup="menu" aria-expanded={open} aria-controls={menuId} disabled={pending === "remove:" + user.userId || pending === "block:" + user.userId} onClick={() => setOpen((value) => !value)}>•••</button>{open && <div id={menuId} role="menu" aria-label={"Thao tác với " + user.displayName} onKeyDown={move}><Link role="menuitem" to={profilePath(user.username)} onClick={() => setOpen(false)}>Xem hồ sơ</Link><button role="menuitem" type="button" disabled={Boolean(pending)} onClick={() => { setOpen(false); onRemove(user); }}>Xóa bạn</button><button role="menuitem" type="button" disabled={Boolean(pending)} onClick={() => { setOpen(false); onBlock(user); }}>Chặn</button></div>}</div>; }
function SearchPanel({ query, onQuery, results, pending, onAdd, onBlock }: { query: string; onQuery: (value: string) => void; results: SocialUser[]; pending: string | null; onAdd: (user: SocialUser) => void; onBlock: (user: SocialUser) => void }) { return <div className="social-panel"><label className="social-search"><span>Tìm theo username hoặc tên hiển thị</span><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Tìm theo username hoặc tên hiển thị" /></label>{query.trim().length >= 2 && results.length === 0 ? <EmptySocial title="Không có kết quả" copy="Thử một username hoặc tên hiển thị khác." /> : <div className="friend-grid">{results.map((user) => <SocialCard key={user.userId} user={user} showPresence={user.isFriend} actions={user.isFriend ? <span className="social-muted">Đã là bạn bè</span> : user.requestStatus ? <span className="social-muted">Đang chờ phản hồi</span> : <><Button pending={pending === "request:" + user.userId} onClick={() => onAdd(user)}>Kết bạn</Button><Button variant="ghost" disabled={Boolean(pending)} onClick={() => onBlock(user)}>Chặn</Button></>} />)}</div>}</div>; }
function Incoming({ requests, invites, refereeInvites, pending, onAcceptRequest, onRejectRequest, onAcceptInvite, onRejectInvite, onAcceptRefInvite, onRejectRefInvite }: { requests: FriendRequest[]; invites: RoomInvite[]; refereeInvites: RefereeInvite[]; pending: string | null; onAcceptRequest: (request: FriendRequest) => void; onRejectRequest: (request: FriendRequest) => void; onAcceptInvite: (invite: RoomInvite) => void; onRejectInvite: (invite: RoomInvite) => void; onAcceptRefInvite: (invite: RefereeInvite) => void; onRejectRefInvite: (invite: RefereeInvite) => void }) { const empty = !requests.length && !invites.length && !refereeInvites.length; return <div className="social-stack">{requests.length > 0 && <RequestList requests={requests} pending={pending} actionLabel="Chấp nhận" onAction={onAcceptRequest} secondary={{ label: "Từ chối", onAction: onRejectRequest }} />}{invites.length > 0 && <section className="invite-inbox" aria-labelledby="room-invites-heading"><p className="eyebrow" id="room-invites-heading">LỜI MỜI VÀO PHÒNG</p>{invites.map((invite) => <InviteRow key={invite.token} avatar={invite.from.displayName.slice(0, 1).toUpperCase()} title={"@" + invite.from.username} detail={"mời bạn vào phòng " + invite.roomId + " · " + (invite.playMode === "BOT" ? "Đấu chương trình" : "Chơi trực tiếp")} expires={invite.expiresAt} pending={pending === invite.token} onAccept={() => onAcceptInvite(invite)} onReject={() => onRejectInvite(invite)} accept="Vào phòng" />)}</section>}{refereeInvites.length > 0 && <section className="invite-inbox referee-invite-inbox" aria-labelledby="referee-invites-heading"><p className="eyebrow" id="referee-invites-heading">LỜI MỜI TRỌNG TÀI</p>{refereeInvites.map((invite) => <InviteRow key={invite.inviteId} avatar="TT" title={invite.from ? "@" + invite.from.username : "Chủ phòng"} detail={"mời bạn làm Trọng tài phòng " + invite.roomId} expires={new Date(invite.expiresAt).toISOString()} pending={pending === invite.inviteId} onAccept={() => onAcceptRefInvite(invite)} onReject={() => onRejectRefInvite(invite)} accept="Nhận vai trò" />)}</section>}{empty && <EmptySocial title="Không có lời mời" copy="Các lời mời kết bạn, vào phòng và Trọng tài sẽ xuất hiện ở đây." />}</div>; }
function InviteRow({ avatar, title, detail, expires, pending, onAccept, onReject, accept }: { avatar: string; title: string; detail: string; expires: string; pending: boolean; onAccept: () => void; onReject: () => void; accept: string }) { return <div className="invite-row"><div className="avatar-mark small" aria-hidden="true">{avatar}</div><div><strong>{title}</strong><span>{detail}</span><small>Hết hạn {formatDate(expires)}</small></div><div><Button pending={pending} onClick={onAccept}>{accept}</Button><Button variant="ghost" disabled={pending} onClick={onReject}>Từ chối</Button></div></div>; }
function RequestList({ requests, pending, actionLabel, onAction, secondary }: { requests: FriendRequest[]; pending: string | null; actionLabel: string; onAction: (request: FriendRequest) => void; secondary?: { label: string; onAction: (request: FriendRequest) => void } }) { return <div className="social-stack">{requests.map((request) => <div className="request-row" key={request.requestId}><div className="avatar-mark small" aria-hidden="true">{request.user.displayName.slice(0, 1).toUpperCase()}</div><div><strong>{request.user.displayName}</strong><span>@{request.user.username}</span><small>{secondary ? "Muốn kết nối với bạn" : "Đang chờ phản hồi"}</small></div><div><Button pending={pending === "request:" + request.requestId} onClick={() => onAction(request)}>{actionLabel}</Button>{secondary && <Button variant="ghost" disabled={Boolean(pending)} onClick={() => secondary.onAction(request)}>{secondary.label}</Button>}</div></div>)}</div>; }
function SocialCard({ user, actions, showPresence = true }: { user: SocialUser; actions: ReactNode; showPresence?: boolean }) { const presence = user.presence ?? "OFFLINE"; return <article className="social-card"><div className="avatar-mark small" aria-hidden="true">{user.displayName.slice(0, 1).toUpperCase()}</div><div className="social-card-copy"><Link to={profilePath(user.username)}><strong>{user.displayName}</strong></Link><span>@{user.username} · Elo {user.elo}</span>{showPresence && <small className={"presence " + presence.toLowerCase()}><i />{presence === "ONLINE" ? "Đang online" : presence === "IN_GAME" ? "Đang chơi" : "Ngoại tuyến"}</small>}<small>{user.rankedWins} thắng · {user.rankedLosses} thua</small></div><div className="social-card-actions">{actions}</div></article>; }
function EmptySocial({ title, copy }: { title: string; copy: string }) { return <div className="social-empty"><div className="social-empty-robot" aria-hidden="true">◈</div><p className="eyebrow">TRỐNG</p><h2>{title}</h2><p>{copy}</p></div>; }
function formatDate(value: string): string { return new Intl.DateTimeFormat("vi-VN", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }
